### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Xanton19** [cqjjjzr/RetroCraft#1]
Hi there,
first of all, thank you very much for the attempt to run Minecraft Forge 1.7.10 to run on Java 11. I have attempted to compile the mod using Gradle 5.0, Java 14.0.1, and forge-1.7.10-1614 with `./gradlew build` and it generated in `build/libs` the jar. But when I put the jar to the 1.7.10 mods folder without any mods installed and start the game with java 11 or 14, it instantly crashes, as if the mod is not functioning. In Java 8 it is as expected working. Here is my compiled jar file, that I have zipped, so I can upload to Github:
[RetroCraft-target-1.0-SNAPSHOT.jar.zip](https://github.com/cqjjjzr/RetroCraft/files/4736410/RetroCraft-target-1.0-SNAPSHOT.jar.zip)

It would be great if you could upload a precompiled jar of the mod, or give instruction on compiling it correctly. Any help is appreciated and I wish you a great day.

**Comment by cqjjjzr** [comment]
The JAR shouldn't be put into the mods folder. It should be attached as a Java Agent jar when starting up JVM. I updated `README.md` with instructions of using RetroCraft.

**Comment by Xanton19** [comment]
Thank you very much, I will try it out.

**Comment by Xanton19** [comment]
So I have put the .jar in my `./minecraft ` folder and added the java agent line into the JVM arguments in the Launcher, but it still crashes. Is something wrong with my build?

**Comment by cqjjjzr** [comment]
Try change the path in the JVM arguments to the absolute path to the JAR file. e.g.

```
-javaagent:"C:/Path/To/JAR/File/RetroCraft-target-1.0-SNAPSHOT.jar"
```

**Comment by cqjjjzr** [comment]
Also, it would help greatly if you could attach the crashing log.

**Comment by Xanton19** [comment]
Thank you for your fast reply. I have just now tried to run with the absolute path to the JAR, but still the same result.

I am sorry that I don't have any crash reports because Minecraft instantly crashes and does not create a log or crash-log.

**Comment by cqjjjzr** [comment]
What launcher are using to launch Minecraft? I have no experience about the official launcher, but for MultiMC the logging should be real time and even when the program crashes before the JVM launches, the log is available.

**Comment by cqjjjzr** [comment]
After a quick Google-fu I find this article which may help: https://minecraftirc.net/support-articles/get-minecraft-log/

**Comment by Xanton19** [comment]
I use the Vanilla launcher and even with the settings you have linked, there is no log. Can you maybe provide your precompiled jar or try the jar I have provided out?

**Comment by cqjjjzr** [comment]
Here is my compiled JAR.

[RetroCraft-target-1.0-SNAPSHOT.zip](https://github.com/cqjjjzr/RetroCraft/files/4736845/RetroCraft-target-1.0-SNAPSHOT.zip)

**Comment by cqjjjzr** [comment]
Obviously your JAR lacks a lot of necessary dependencies, there may be some issues within your build process. You need to build with `./gradlew targetJar`.

**Comment by Xanton19** [comment]
This is now my crash report with OpenJDK 11:
> 17:28:07.263
> Starting!
> 17:28:07.401
> Using default game log configuration client-1.7.xml (outputs XML)
> 17:28:08.472
> Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=cn/ac/origind/retrocraft/RetroCraftAgent, offset=6
> 	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:476)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:437)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1110)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:898)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:806)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:764)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
> 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
> 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
> *** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
> 
> Fatal error: processing of -javaagent failed, processJavaStart failed
> 17:28:08.472
> Process crashed with exit code 1111

**Comment by Xanton19** [comment]
This is with Java OpenJDK 14:

> 17:36:09.430
> Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
> 17:36:09.430
> Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
> 17:36:09.493
> [cn.ac.origind.retrocraft.ForgeTransformer:transform:35]: [2020-06-05T15:36:09.492664500Z] [RetroCraft] Patching org/objectweb/asm/ClassReader.
> 17:36:09.726
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: java.util.jar.Pack200
> 	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:161)
> 	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
> 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:788)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
> 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1183)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1098)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
> 	... 5 more
> 17:36:09.726
> Process crashed with exit code 1

**Comment by Xanton19** [comment]
I have solved the problem. The JVM arguments need to begin with `-client -javaagent:C:\LinkToJar\RetroCraft-target-1.0-SNAPSHOT.jar` and it works with JDK 13 but for some reason not JDK 14 or JDK 11. Thank you very much for your help and have a nice day!

**Comment by cqjjjzr** [comment]
I just tested with Oracle JDK 12 and it runs successfully. The patch doesn't support JDK 11(the patched classes' class version is set to JDK 12). `java.util.jar.Pack200` class is removed in Java 14(JEP-367). A solution against this removal need to be applied.
